package io.nuls.api.entity;

import java.util.ArrayList;
import java.util.List;

public class MinedTopParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected int count = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public MinedTopParam() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public void setCount(int count) {
        this.count=count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public int getCount() {
        return count;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAgentAddressIsNull() {
            addCriterion("agent_address is null");
            return (Criteria) this;
        }

        public Criteria andAgentAddressIsNotNull() {
            addCriterion("agent_address is not null");
            return (Criteria) this;
        }

        public Criteria andAgentAddressEqualTo(String value) {
            addCriterion("agent_address =", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotEqualTo(String value) {
            addCriterion("agent_address <>", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressGreaterThan(String value) {
            addCriterion("agent_address >", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("agent_address >=", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLessThan(String value) {
            addCriterion("agent_address <", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLessThanOrEqualTo(String value) {
            addCriterion("agent_address <=", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLike(String value) {
            addCriterion("agent_address like", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotLike(String value) {
            addCriterion("agent_address not like", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressIn(List<String> values) {
            addCriterion("agent_address in", values, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotIn(List<String> values) {
            addCriterion("agent_address not in", values, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressBetween(String value1, String value2) {
            addCriterion("agent_address between", value1, value2, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotBetween(String value1, String value2) {
            addCriterion("agent_address not between", value1, value2, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressIsNull() {
            addCriterion("consensus_address is null");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressIsNotNull() {
            addCriterion("consensus_address is not null");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressEqualTo(String value) {
            addCriterion("consensus_address =", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressNotEqualTo(String value) {
            addCriterion("consensus_address <>", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressGreaterThan(String value) {
            addCriterion("consensus_address >", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressGreaterThanOrEqualTo(String value) {
            addCriterion("consensus_address >=", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressLessThan(String value) {
            addCriterion("consensus_address <", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressLessThanOrEqualTo(String value) {
            addCriterion("consensus_address <=", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressLike(String value) {
            addCriterion("consensus_address like", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressNotLike(String value) {
            addCriterion("consensus_address not like", value, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressIn(List<String> values) {
            addCriterion("consensus_address in", values, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressNotIn(List<String> values) {
            addCriterion("consensus_address not in", values, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressBetween(String value1, String value2) {
            addCriterion("consensus_address between", value1, value2, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressNotBetween(String value1, String value2) {
            addCriterion("consensus_address not between", value1, value2, "consensusAddress");
            return (Criteria) this;
        }

        public Criteria andMinedCountIsNull() {
            addCriterion("mined_count is null");
            return (Criteria) this;
        }

        public Criteria andMinedCountIsNotNull() {
            addCriterion("mined_count is not null");
            return (Criteria) this;
        }

        public Criteria andMinedCountEqualTo(Integer value) {
            addCriterion("mined_count =", value, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountNotEqualTo(Integer value) {
            addCriterion("mined_count <>", value, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountGreaterThan(Integer value) {
            addCriterion("mined_count >", value, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("mined_count >=", value, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountLessThan(Integer value) {
            addCriterion("mined_count <", value, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountLessThanOrEqualTo(Integer value) {
            addCriterion("mined_count <=", value, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountIn(List<Integer> values) {
            addCriterion("mined_count in", values, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountNotIn(List<Integer> values) {
            addCriterion("mined_count not in", values, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountBetween(Integer value1, Integer value2) {
            addCriterion("mined_count between", value1, value2, "minedCount");
            return (Criteria) this;
        }

        public Criteria andMinedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("mined_count not between", value1, value2, "minedCount");
            return (Criteria) this;
        }

        public Criteria andRewardIsNull() {
            addCriterion("reward is null");
            return (Criteria) this;
        }

        public Criteria andRewardIsNotNull() {
            addCriterion("reward is not null");
            return (Criteria) this;
        }

        public Criteria andRewardEqualTo(Long value) {
            addCriterion("reward =", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotEqualTo(Long value) {
            addCriterion("reward <>", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThan(Long value) {
            addCriterion("reward >", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardGreaterThanOrEqualTo(Long value) {
            addCriterion("reward >=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThan(Long value) {
            addCriterion("reward <", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardLessThanOrEqualTo(Long value) {
            addCriterion("reward <=", value, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardIn(List<Long> values) {
            addCriterion("reward in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotIn(List<Long> values) {
            addCriterion("reward not in", values, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardBetween(Long value1, Long value2) {
            addCriterion("reward between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andRewardNotBetween(Long value1, Long value2) {
            addCriterion("reward not between", value1, value2, "reward");
            return (Criteria) this;
        }

        public Criteria andLastHeightIsNull() {
            addCriterion("last_height is null");
            return (Criteria) this;
        }

        public Criteria andLastHeightIsNotNull() {
            addCriterion("last_height is not null");
            return (Criteria) this;
        }

        public Criteria andLastHeightEqualTo(Long value) {
            addCriterion("last_height =", value, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightNotEqualTo(Long value) {
            addCriterion("last_height <>", value, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightGreaterThan(Long value) {
            addCriterion("last_height >", value, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightGreaterThanOrEqualTo(Long value) {
            addCriterion("last_height >=", value, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightLessThan(Long value) {
            addCriterion("last_height <", value, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightLessThanOrEqualTo(Long value) {
            addCriterion("last_height <=", value, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightIn(List<Long> values) {
            addCriterion("last_height in", values, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightNotIn(List<Long> values) {
            addCriterion("last_height not in", values, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightBetween(Long value1, Long value2) {
            addCriterion("last_height between", value1, value2, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andLastHeightNotBetween(Long value1, Long value2) {
            addCriterion("last_height not between", value1, value2, "lastHeight");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLikeInsensitive(String value) {
            addCriterion("upper(agent_address) like", value.toUpperCase(), "agentAddress");
            return (Criteria) this;
        }

        public Criteria andConsensusAddressLikeInsensitive(String value) {
            addCriterion("upper(consensus_address) like", value.toUpperCase(), "consensusAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mined_top
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mined_top
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}