package io.nuls.api.entity;

import java.io.Serializable;

public class TxHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_history.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_history.tx_date
     *
     * @mbggenerated
     */
    private String txDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_history.tx_count
     *
     * @mbggenerated
     */
    private Integer txCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_history.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_history.id
     *
     * @return the value of tx_history.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_history.id
     *
     * @param id the value for tx_history.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_history.tx_date
     *
     * @return the value of tx_history.tx_date
     *
     * @mbggenerated
     */
    public String getTxDate() {
        return txDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_history.tx_date
     *
     * @param txDate the value for tx_history.tx_date
     *
     * @mbggenerated
     */
    public void setTxDate(String txDate) {
        this.txDate = txDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_history.tx_count
     *
     * @return the value of tx_history.tx_count
     *
     * @mbggenerated
     */
    public Integer getTxCount() {
        return txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_history.tx_count
     *
     * @param txCount the value for tx_history.tx_count
     *
     * @mbggenerated
     */
    public void setTxCount(Integer txCount) {
        this.txCount = txCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_history.create_time
     *
     * @return the value of tx_history.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_history.create_time
     *
     * @param createTime the value for tx_history.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TxHistory other = (TxHistory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTxDate() == null ? other.getTxDate() == null : this.getTxDate().equals(other.getTxDate()))
            && (this.getTxCount() == null ? other.getTxCount() == null : this.getTxCount().equals(other.getTxCount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTxDate() == null) ? 0 : getTxDate().hashCode());
        result = prime * result + ((getTxCount() == null) ? 0 : getTxCount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", txDate=").append(txDate);
        sb.append(", txCount=").append(txCount);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}