package io.nuls.api.server.business;

import io.nuls.api.entity.BalanceTop;
import io.nuls.api.entity.BalanceTopParam;
import io.nuls.api.server.dao.mapper.BalanceTopMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
public class BalanceTopBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    private static Logger logger = LoggerFactory.getLogger(BalanceTopBusiness.class);

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    @Autowired 
    private BalanceTopMapper balanceTopMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int insertSelective(BalanceTop obj) throws Exception {
        if(obj  == null ){
            return 0;
        }
        return this.balanceTopMapper.insertSelective(obj);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int insertSelective(List<BalanceTop> list) throws Exception {
        int insertCount = 0;
        if (list == null || list.size() == 0) {
            return insertCount;
        }
        for (BalanceTop  obj : list) {
            if (obj == null) {
                continue;
            }
            try {
                insertCount += this.balanceTopMapper.insertSelective(obj);
            } catch (Exception e) {
                throw e;
            }
        }
        return insertCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    public BalanceTop getBalanceTopByKey(Long key) throws Exception {
        return this.balanceTopMapper.selectByPrimaryKey(key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int update(BalanceTop obj) throws Exception {
        if(obj  == null ){
            return 0;
        }
        return this.balanceTopMapper.updateByPrimaryKeySelective(obj);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int update(List<BalanceTop> list) throws Exception {
        int updateCount = 0;
        if (list == null || list.size() == 0) {
            return updateCount;
        }
        for (BalanceTop  obj : list) {
            if (obj == null || obj.getId() == null || obj.getId() <= 0 ) {
                continue;
            }
            try {
                updateCount += this.balanceTopMapper.updateByPrimaryKeySelective(obj);
            } catch (Exception e) {
                throw e;
            }
        }
        return updateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    public List<BalanceTop> selectBalanceTopList(BalanceTopParam param) throws Exception {
        return this.balanceTopMapper.selectByExample(param);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    public int countBalanceTopList(BalanceTopParam param) throws Exception {
        return this.balanceTopMapper.countByExample(param);
    }
}