package io.nuls.api.server.business;

import io.nuls.api.entity.TxHistory;
import io.nuls.api.entity.TxHistoryParam;
import io.nuls.api.server.dao.mapper.TxHistoryMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
public class TxHistoryBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    private static Logger logger = LoggerFactory.getLogger(TxHistoryBusiness.class);

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Autowired 
    private TxHistoryMapper txHistoryMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int insertSelective(TxHistory obj) throws Exception {
        if(obj  == null ){
            return 0;
        }
        return this.txHistoryMapper.insertSelective(obj);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int insertSelective(List<TxHistory> list) throws Exception {
        int insertCount = 0;
        if (list == null || list.size() == 0) {
            return insertCount;
        }
        for (TxHistory  obj : list) {
            if (obj == null) {
                continue;
            }
            try {
                insertCount += this.txHistoryMapper.insertSelective(obj);
            } catch (Exception e) {
                throw e;
            }
        }
        return insertCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    public TxHistory getTxHistoryByKey(Long key) throws Exception {
        return this.txHistoryMapper.selectByPrimaryKey(key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int update(TxHistory obj) throws Exception {
        if(obj  == null ){
            return 0;
        }
        return this.txHistoryMapper.updateByPrimaryKeySelective(obj);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int update(List<TxHistory> list) throws Exception {
        int updateCount = 0;
        if (list == null || list.size() == 0) {
            return updateCount;
        }
        for (TxHistory  obj : list) {
            if (obj == null || obj.getId() == null || obj.getId() <= 0 ) {
                continue;
            }
            try {
                updateCount += this.txHistoryMapper.updateByPrimaryKeySelective(obj);
            } catch (Exception e) {
                throw e;
            }
        }
        return updateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    public List<TxHistory> selectTxHistoryList(TxHistoryParam param) throws Exception {
        return this.txHistoryMapper.selectByExample(param);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    public int countTxHistoryList(TxHistoryParam param) throws Exception {
        return this.txHistoryMapper.countByExample(param);
    }
}