package io.nuls.api.server.dao.mapper;

import io.nuls.api.entity.Alias;
import io.nuls.api.entity.AliasParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AliasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int countByExample(AliasParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int deleteByExample(AliasParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alias);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int insert(Alias record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int insertSelective(Alias record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    List<Alias> selectByExample(AliasParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    Alias selectByPrimaryKey(String alias);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Alias record, @Param("example") AliasParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Alias record, @Param("example") AliasParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Alias record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alias
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Alias record);
}