package io.nuls.api.server.dao.mapper;

import io.nuls.api.entity.BalanceTop;
import io.nuls.api.entity.BalanceTopParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BalanceTopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int countByExample(BalanceTopParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int deleteByExample(BalanceTopParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int insert(BalanceTop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int insertSelective(BalanceTop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    List<BalanceTop> selectByExample(BalanceTopParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    BalanceTop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BalanceTop record, @Param("example") BalanceTopParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BalanceTop record, @Param("example") BalanceTopParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BalanceTop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_top
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BalanceTop record);
}