package io.nuls.api.server.dao.mapper;

import io.nuls.api.entity.TxHistory;
import io.nuls.api.entity.TxHistoryParam;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TxHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int countByExample(TxHistoryParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int deleteByExample(TxHistoryParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int insert(TxHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int insertSelective(TxHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    List<TxHistory> selectByExample(TxHistoryParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    TxHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TxHistory record, @Param("example") TxHistoryParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TxHistory record, @Param("example") TxHistoryParam example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TxHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TxHistory record);
}